---
- name: Install default Apache Web Server
  hosts: webservers
  become: yes

  tasks:
  - name: Install Apache WebServer
    apt: name=apache2 state=latest
  
  - name: Start Apache and enable
    service: name=apache2 state=started enabled=yes